__include__:
  - './common_73e.yml'

output_dir: ${OUTPUT_ROOT}/paper_73e/B3_FullISA_S42
seed: 42
# ISA ablation: full ISA.
FusionDETR:
  use_purification: True
  use_alignment: True

HybridEncoder:
  use_channel_attention: False
  use_spatial_attention: False
