__include__:
  - './common_73e.yml'

output_dir: ${OUTPUT_ROOT}/paper_73e/DV_Full_S44
seed: 44
# Full model (IV-PAFNet), seed 44.
FusionDETR:
  use_purification: True
  use_alignment: True

HybridEncoder:
  use_channel_attention: True
  use_spatial_attention: True
